name = "archiwum-worker"
main = "src/index.js"
compatibility_date = "2025-10-01"

[env.production]
name = "archiwum-api"

# Route for existing domain (optional)
# routes = ["example.com/api/*"]

[[d1_databases]]
binding = "ARCHIWUM_DB"
database_name = "archiwum-danych"
# Archiwalna baza (tylko odczyt)
database_id = "b0db5c41-2ccc-48d4-ba3e-d37a017b13fd"

[[d1_databases]]
binding = "PRODUCTION_DB"
database_name = "archiwum-produkcja"
# Produkcyjna baza z CRUD
database_id = "a4627ed8-c467-42eb-8469-e3c24eb28e83"